# Generated by Django 4.2.29 on 2026-03-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentinfo',
            name='contact_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
