# Generated by Django 4.2.29 on 2026-03-09 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_add_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.PositiveSmallIntegerField(help_text='Player position (1-based)')),
                ('name', models.CharField(blank=True, help_text='Leave blank if unknown', max_length=200)),
                ('registration', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournament.registration')),
            ],
            options={
                'ordering': ['slot'],
                'unique_together': {('registration', 'slot')},
            },
        ),
    ]
