# Generated by Django 4.2.29 on 2026-03-09 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_add_addon_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Optional company logo (displayed on the tournament website)', null=True, upload_to='registration_logos/'),
        ),
        migrations.AddField(
            model_name='sponsorshippackage',
            name='logo_upload',
            field=models.BooleanField(default=False, help_text='Allow registrants to upload a company logo with this package'),
        ),
    ]
