# Generated by Django 4.2.29 on 2026-03-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_add_logo_upload_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsorshippackage',
            name='sponsor_tier',
            field=models.CharField(blank=True, choices=[('', 'None (no logo display)'), ('gold', 'Gold'), ('silver', 'Silver'), ('bronze', 'Bronze'), ('other', 'Community Supporters')], default='', help_text='Tier under which registrant logos are displayed on the home page', max_length=20),
        ),
    ]
